apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    ops-union.dev/environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    ops-union.dev/environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    ops-union.dev/environment: local
