import { X } from 'lucide-react';
import type { LogEventRecord } from '../types';
import type { LogGrouping } from '../logsPresentation';

export type LogConnectionState = 'validating' | 'connecting' | 'reconnecting' | 'streaming' | 'paused' | 'ended' | 'partial' | 'error' | 'history-starting' | 'history-reading' | 'history-ready' | 'history-partial' | 'history-cancelled' | 'history-expired' | 'transitioning';
export type LogHistoryStatus = 'starting' | 'reading' | 'complete' | 'partial' | 'failed' | 'cancelled' | 'expired' | 'transitioning' | 'transition-failed' | 'transitioned';

export function FilterSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) {
  return <label className={`log-control log-filter-select ${value ? 'is-selected' : 'is-empty'}`} data-state={value ? 'selected' : 'empty'}><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} aria-label={`Filter by ${label.toLowerCase()}`}><option value="">All {label.toLowerCase()}s</option>{values.map((option) => <option value={option} key={option}>{option}</option>)}</select>{value && <button type="button" className="filter-clear" onClick={() => onChange('')} aria-label={`Clear ${label.toLowerCase()} filter`}><X size={11} aria-hidden="true" /></button>}</label>;
}

export function LogRow({ record, grouping, query, start, wrapLines, measureElement, index }: { record: LogEventRecord; grouping: LogGrouping; query: string; start: number; wrapLines: boolean; measureElement: (element: HTMLElement) => void; index: number }) {
  const group = grouping === 'application' ? record.source.application?.name ?? record.source.pod : record.source.container;
  const message = record.event.message || '(empty message)';
  return <div ref={(element) => { if (element) measureElement(element); }} data-index={index} className={`log-line structured-log-line ${wrapLines ? 'is-wrapped' : 'is-nowrap'}`} style={{ position: 'absolute', top: 0, left: 0, width: '100%', transform: `translateY(${start}px)` }}>
    <span className="log-source-cell" title={`${record.source.pod} / ${record.source.container}`}><strong>{group}</strong><small>{record.source.pod} / {record.source.container}</small></span>
    <span className="log-message" aria-label={message}>{highlightSegments(message, query).map((segment, segmentIndex) => segment.match ? <mark className="log-mark" key={segmentIndex}>{segment.text}</mark> : <span key={segmentIndex}>{segment.text}</span>)}</span>
  </div>;
}

export function LogRowPlaceholder({ start, wrapLines, measureElement, index }: { start: number; wrapLines: boolean; measureElement: (element: HTMLElement) => void; index: number }) {
  return <div ref={(element) => { if (element) measureElement(element); }} data-index={index} className={`log-line structured-log-line log-query-placeholder ${wrapLines ? 'is-wrapped' : 'is-nowrap'}`} style={{ position: 'absolute', top: 0, left: 0, width: '100%', transform: `translateY(${start}px)` }} aria-label="Loading historical record"><span className="log-source-cell" aria-hidden="true"><strong>...</strong><small>loading</small></span><span className="log-message" aria-hidden="true">Loading historical record...</span></div>;
}

export function stateLabel(state: LogConnectionState): string { if (state === 'validating') return 'validating'; if (state === 'connecting') return 'connecting'; if (state === 'reconnecting') return 'reconnecting'; if (state === 'streaming') return 'live'; if (state === 'paused') return 'paused'; if (state === 'partial' || state === 'history-partial') return 'partial'; if (state === 'history-starting') return 'history starting'; if (state === 'history-reading') return 'reading history'; if (state === 'history-ready') return 'history ready'; if (state === 'history-cancelled') return 'history cancelled'; if (state === 'history-expired') return 'history expired'; if (state === 'transitioning') return 'starting live'; if (state === 'error') return 'error'; return 'ended'; }
export function historyStatusLabel(status: LogHistoryStatus): string { if (status === 'starting') return 'History session starting'; if (status === 'reading') return 'Preparing historical snapshot'; if (status === 'complete') return 'Historical snapshot ready'; if (status === 'partial') return 'Historical snapshot partial'; if (status === 'failed') return 'Historical snapshot failed'; if (status === 'cancelled') return 'Historical snapshot cancelled'; if (status === 'expired') return 'Historical snapshot expired'; if (status === 'transitioning') return 'Historical boundary retained while Live connects'; if (status === 'transition-failed') return 'Live transition failed; history retained'; return 'Historical boundary closed; Live acknowledged'; }
export function emptyMessage(state: LogConnectionState, mode: 'live' | 'history', history: { status: LogHistoryStatus } | undefined, windowLoading: boolean, windowError: string | undefined, eventCount: number, filterCount: number): string { if (filterCount > 0 && eventCount > 0) return 'No event matches the selected filters.'; if (mode === 'history') { if (state === 'history-starting' || state === 'history-reading') return 'Preparing the historical snapshot...'; if (windowError) return 'The historical window could not be loaded. Retry the window request.'; if (windowLoading) return 'Loading historical window...'; if (history?.status === 'cancelled') return 'History was cancelled. Start a new Search to begin again.'; if (history?.status === 'expired') return 'This historical snapshot expired. Start a new Search to prepare it again.'; if (history?.status === 'failed') return 'The historical snapshot failed without readable records.'; if (history?.status === 'complete' || history?.status === 'partial') return 'The historical snapshot contains no records.'; } return state === 'connecting' || state === 'transitioning' ? 'Connecting to selected sources...' : 'No log events received yet.'; }
export function formatRange(range?: { from?: string; to?: string }): string { if (!range || (!range.from && !range.to)) return 'Range: all available'; return `Range: ${range.from ?? 'all available'} to ${range.to ?? 'now'} (UTC, end exclusive)`; }
export function formatBytes(bytes: number): string { if (bytes >= 1024 * 1024) return `${Math.round(bytes / (1024 * 1024))} MiB`; if (bytes >= 1024) return `${Math.round(bytes / 1024)} KiB`; return `${bytes} B`; }

function highlightSegments(value: string, query: string): Array<{ text: string; match: boolean }> { const needle = query.trim(); if (!needle) return [{ text: value, match: false }]; const lower = value.toLowerCase(); const lowerNeedle = needle.toLowerCase(); const segments: Array<{ text: string; match: boolean }> = []; let cursor = 0; let index = lower.indexOf(lowerNeedle); while (index >= 0) { if (index > cursor) segments.push({ text: value.slice(cursor, index), match: false }); segments.push({ text: value.slice(index, index + needle.length), match: true }); cursor = index + needle.length; index = lower.indexOf(lowerNeedle, cursor); } if (cursor < value.length) segments.push({ text: value.slice(cursor), match: false }); return segments.length > 0 ? segments : [{ text: value, match: false }]; }